-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 14:02:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adminsion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adminsion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adminsion` DEFAULT CHARACTER SET utf8 ;
USE `adminsion` ;

-- -----------------------------------------------------
-- Table `adminsion`.`datosubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datosubicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `codigopostal` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datosfamiliares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datosfamiliares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombrepadre` VARCHAR(45) NULL,
  `apellidopaternopadre` VARCHAR(45) NULL,
  `apellidomaternopadre` VARCHAR(45) NULL,
  `direccionpadre` VARCHAR(45) NULL,
  `celularpadre` VARCHAR(45) NULL,
  `ocupacionpadre` VARCHAR(45) NULL,
  `nombremadre` VARCHAR(45) NULL,
  `apellidopaternomadre` VARCHAR(45) NULL,
  `apellidomaternomadre` VARCHAR(45) NULL,
  `direccionmadre` VARCHAR(45) NULL,
  `celularmadre` VARCHAR(45) NULL,
  `ocupacionmadre` VARCHAR(45) NULL,
  `estadocivil` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datosfinancieros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datosfinancieros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidopaterno` VARCHAR(45) NULL,
  `apellidomaterno` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `iddatosubicacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datosfinancieros_datosubicacion1_idx` (`iddatosubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_datosfinancieros_datosubicacion1`
    FOREIGN KEY (`iddatosubicacion`)
    REFERENCES `adminsion`.`datosubicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datosreligion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datosreligion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `religion` VARCHAR(45) NULL,
  `bautizado` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `asociacionmision` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`enterado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`enterado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datosacademicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datosacademicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrera` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`tiposangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`tiposangre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datossalud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datossalud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `impedimendofisico` VARCHAR(45) NULL,
  `enfermedadalergia` VARCHAR(45) NULL,
  `seguro` VARCHAR(45) NULL,
  `idtiposangre` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datos_salud_tiposangre1_idx` (`idtiposangre` ASC) VISIBLE,
  CONSTRAINT `fk_datos_salud_tiposangre1`
    FOREIGN KEY (`idtiposangre`)
    REFERENCES `adminsion`.`tiposangre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`datospersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`datospersonales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lugarnacimiento` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `fechanacimiento` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `estadocivil` VARCHAR(45) NOT NULL,
  `trabajo` VARCHAR(45) NULL,
  `porcentajebeca` INT NULL,
  `beca` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adminsion`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adminsion`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidopaterno` VARCHAR(45) NOT NULL,
  `apellidomaterno` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `iddatosubicacion` INT NOT NULL,
  `iddatosfamiliares` INT NOT NULL,
  `iddatosfinancieros` INT NOT NULL,
  `iddatosreligion` INT NOT NULL,
  `identerado` INT NOT NULL,
  `iddatosacademicos` INT NOT NULL,
  `iddatossalud` INT NOT NULL,
  `iddatospersonales` INT NOT NULL,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_datosubicacion1_idx` (`iddatosubicacion` ASC) VISIBLE,
  INDEX `fk_usuarios_datosfamiliares1_idx` (`iddatosfamiliares` ASC) VISIBLE,
  INDEX `fk_usuarios_datosfinancieros1_idx` (`iddatosfinancieros` ASC) VISIBLE,
  INDEX `fk_usuarios_datosreligion1_idx` (`iddatosreligion` ASC) VISIBLE,
  INDEX `fk_usuarios_enterado1_idx` (`identerado` ASC) VISIBLE,
  INDEX `fk_usuarios_datosacademicos1_idx` (`iddatosacademicos` ASC) VISIBLE,
  INDEX `fk_usuarios_datossalud1_idx` (`iddatossalud` ASC) VISIBLE,
  INDEX `fk_usuarios_datospersonales1_idx` (`iddatospersonales` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_datosubicacion1`
    FOREIGN KEY (`iddatosubicacion`)
    REFERENCES `adminsion`.`datosubicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datosfamiliares1`
    FOREIGN KEY (`iddatosfamiliares`)
    REFERENCES `adminsion`.`datosfamiliares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datosfinancieros1`
    FOREIGN KEY (`iddatosfinancieros`)
    REFERENCES `adminsion`.`datosfinancieros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datosreligion1`
    FOREIGN KEY (`iddatosreligion`)
    REFERENCES `adminsion`.`datosreligion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_enterado1`
    FOREIGN KEY (`identerado`)
    REFERENCES `adminsion`.`enterado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datosacademicos1`
    FOREIGN KEY (`iddatosacademicos`)
    REFERENCES `adminsion`.`datosacademicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datossalud1`
    FOREIGN KEY (`iddatossalud`)
    REFERENCES `adminsion`.`datossalud` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_datospersonales1`
    FOREIGN KEY (`iddatospersonales`)
    REFERENCES `adminsion`.`datospersonales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
